"""Report generation and formatting."""

import logging
from typing import List, Dict, Any, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates formatted reports from news data."""
    
    def generate_html_report(
        self,
        articles: List[Dict[str, Any]],
        analysis: str,
        prompt: str,
        report_type: str = "instant"
    ) -> str:
        """
        Generate an HTML email report.
        
        Args:
            articles: List of news articles
            analysis: Analyzed news content from DeepSeek
            prompt: Original search prompt
            report_type: Type of report (instant, scheduled, aggregate)
            
        Returns:
            HTML string
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Build articles HTML
        articles_html = ""
        for i, article in enumerate(articles, 1):
            articles_html += f"""
            <div style="margin-bottom: 20px; padding: 15px; background-color: #f8f9fa; border-left: 4px solid #007bff; border-radius: 4px;">
                <h3 style="margin-top: 0; color: #007bff;">
                    {i}. {article.get('title', 'No Title')}
                </h3>
                <p style="margin: 5px 0; color: #6c757d; font-size: 0.9em;">
                    <strong>Source:</strong> {article.get('source', 'Unknown')}
                </p>
                {f'<p style="margin: 5px 0;"><a href="{article.get("url")}" style="color: #007bff; text-decoration: none;">Read Article →</a></p>' if article.get('url') and article.get('url') != 'N/A' else ''}
                <p style="margin: 10px 0 0 0;">
                    {article.get('snippet', 'No description available.')}
                </p>
            </div>
            """
        
        # Build full HTML
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>News Report</title>
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px;">
            
            <!-- Header -->
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
                <h1 style="margin: 0 0 10px 0; font-size: 28px;">📰 News Aggregation Report</h1>
                <p style="margin: 0; opacity: 0.9; font-size: 14px;">
                    <strong>Type:</strong> {report_type.capitalize()} Report<br>
                    <strong>Generated:</strong> {timestamp}<br>
                    <strong>Query:</strong> "{prompt}"
                </p>
            </div>
            
            <!-- Analysis Section -->
            <div style="margin-bottom: 30px;">
                <h2 style="color: #667eea; border-bottom: 2px solid #667eea; padding-bottom: 10px;">
                    🔍 Analysis & Summary
                </h2>
                <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; white-space: pre-wrap;">
                    {analysis}
                </div>
            </div>
            
            <!-- Articles Section -->
            <div style="margin-bottom: 30px;">
                <h2 style="color: #667eea; border-bottom: 2px solid #667eea; padding-bottom: 10px;">
                    📑 News Articles ({len(articles)})
                </h2>
                {articles_html}
            </div>
            
            <!-- Footer -->
            <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e9ecef; text-align: center; color: #6c757d; font-size: 0.9em;">
                <p>Generated by News Aggregation System with DeepSeek AI</p>
                <p style="margin: 5px 0;">Powered by LangChain & Python</p>
            </div>
            
        </body>
        </html>
        """
        
        return html
    
    def generate_text_report(
        self,
        articles: List[Dict[str, Any]],
        analysis: str,
        prompt: str,
        report_type: str = "instant"
    ) -> str:
        """
        Generate a plain text report.
        
        Args:
            articles: List of news articles
            analysis: Analyzed news content
            prompt: Original search prompt
            report_type: Type of report
            
        Returns:
            Plain text string
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        report = f"""
{'=' * 80}
NEWS AGGREGATION REPORT
{'=' * 80}

Type: {report_type.capitalize()} Report
Generated: {timestamp}
Query: "{prompt}"

{'=' * 80}
ANALYSIS & SUMMARY
{'=' * 80}

{analysis}

{'=' * 80}
NEWS ARTICLES ({len(articles)})
{'=' * 80}

"""
        
        for i, article in enumerate(articles, 1):
            report += f"""
{i}. {article.get('title', 'No Title')}
   Source: {article.get('source', 'Unknown')}
   URL: {article.get('url', 'N/A')}
   
   {article.get('snippet', 'No description available.')}

{'-' * 80}
"""
        
        report += f"""
{'=' * 80}
Generated by News Aggregation System with DeepSeek AI
Powered by LangChain & Python
{'=' * 80}
"""
        
        return report
    
    def generate_aggregate_report(
        self,
        all_articles: List[List[Dict[str, Any]]],
        aggregate_analysis: str,
        prompt: str,
        start_date: datetime,
        end_date: datetime
    ) -> str:
        """
        Generate an aggregate HTML report from multiple monitoring sessions.
        
        Args:
            all_articles: List of article lists from each session
            aggregate_analysis: Combined analysis from DeepSeek
            prompt: Original search prompt
            start_date: Start of monitoring period
            end_date: End of monitoring period
            
        Returns:
            HTML string
        """
        total_articles = sum(len(articles) for articles in all_articles)
        num_sessions = len(all_articles)
        
        # Flatten and deduplicate articles
        seen_urls = set()
        unique_articles = []
        for articles in all_articles:
            for article in articles:
                url = article.get('url', '')
                if url and url != 'N/A' and url not in seen_urls:
                    seen_urls.add(url)
                    unique_articles.append(article)
                elif not url or url == 'N/A':
                    unique_articles.append(article)
        
        # Generate articles HTML
        articles_html = ""
        for i, article in enumerate(unique_articles[:50], 1):  # Limit to top 50
            articles_html += f"""
            <div style="margin-bottom: 20px; padding: 15px; background-color: #f8f9fa; border-left: 4px solid #28a745; border-radius: 4px;">
                <h3 style="margin-top: 0; color: #28a745;">
                    {i}. {article.get('title', 'No Title')}
                </h3>
                <p style="margin: 5px 0; color: #6c757d; font-size: 0.9em;">
                    <strong>Source:</strong> {article.get('source', 'Unknown')}
                </p>
                {f'<p style="margin: 5px 0;"><a href="{article.get("url")}" style="color: #28a745; text-decoration: none;">Read Article →</a></p>' if article.get('url') and article.get('url') != 'N/A' else ''}
                <p style="margin: 10px 0 0 0;">
                    {article.get('snippet', 'No description available.')}
                </p>
            </div>
            """
        
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Aggregate News Report</title>
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px;">
            
            <!-- Header -->
            <div style="background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px;">
                <h1 style="margin: 0 0 10px 0; font-size: 28px;">📊 Aggregate News Report</h1>
                <p style="margin: 0; opacity: 0.9; font-size: 14px;">
                    <strong>Period:</strong> {start_date.strftime("%Y-%m-%d %H:%M")} to {end_date.strftime("%Y-%m-%d %H:%M")}<br>
                    <strong>Query:</strong> "{prompt}"<br>
                    <strong>Monitoring Sessions:</strong> {num_sessions}<br>
                    <strong>Total Articles Found:</strong> {total_articles}<br>
                    <strong>Unique Articles:</strong> {len(unique_articles)}
                </p>
            </div>
            
            <!-- Aggregate Analysis -->
            <div style="margin-bottom: 30px;">
                <h2 style="color: #11998e; border-bottom: 2px solid #11998e; padding-bottom: 10px;">
                    🔍 Aggregate Analysis
                </h2>
                <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; white-space: pre-wrap;">
                    {aggregate_analysis}
                </div>
            </div>
            
            <!-- All Articles -->
            <div style="margin-bottom: 30px;">
                <h2 style="color: #11998e; border-bottom: 2px solid #11998e; padding-bottom: 10px;">
                    📑 Unique Articles ({len(unique_articles)})
                </h2>
                {articles_html}
            </div>
            
            <!-- Footer -->
            <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e9ecef; text-align: center; color: #6c757d; font-size: 0.9em;">
                <p>Aggregate Report Generated by News Aggregation System with DeepSeek AI</p>
                <p style="margin: 5px 0;">Powered by LangChain & Python</p>
            </div>
            
        </body>
        </html>
        """
        
        return html
